import pandas as pd
data=pd.read_csv('../data/tips.csv')
#print(data.isna().any())
#print(data.isna().sum())
tips_male_female=data.filter(['tip','smoker'])
#print(tips_male_female.groupby('sex').sum())
#print(tips_male_female.smoker.value_counts())
#print(pd.crosstab(index=data['sex'],columns=data['smoker']))
#print(pd.crosstab(index=data['day'],values=data['tip']))
data1=data.filter(['tip','day'])
#print(data1.groupby('day').sum())
#print(data.info())
#print(data.describe())
#print(data.head(2))
print(tips_male_female)